const fightersArray = [
    {
        name: 'Manny',
        expPoints: 0,
        barPoints: 0,
        level: 1,
        classesBoxing: 0,
        classesMuayThai: 0,
        classesWrestling: 0,
        classesJiuJitsu: 0,
        dataName: 'manny',
    },
    {
        name: 'Anabella',
        expPoints: 0,
        barPoints: 0,
        level: 1,
        classesBoxing: 0,
        classesMuayThai: 0,
        classesWrestling: 0,
        classesJiuJitsu: 0,
        dataName: 'anabella',
    },
    {
        name: 'Adan',
        expPoints: 0,
        barPoints: 0,
        level: 1,
        classesBoxing: 0,
        classesMuayThai: 0,
        classesWrestling: 0,
        classesJiuJitsu: 0,
        dataName: 'adan',
    },
    {
        name: 'Nick',
        expPoints: 0,
        barPoints: 0,
        level: 1,
        classesBoxing: 0,
        classesMuayThai: 0,
        classesWrestling: 0,
        classesJiuJitsu: 0,
        dataName: 'nick',
    },
]

export default fightersArray